# Generated by Django 4.0.2 on 2022-03-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_post_message_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='update',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
