# Generated by Django 4.0.2 on 2022-03-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_room_update_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='post',
            new_name='host',
        ),
    ]
